### ISSUE TITLE
Create a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by TanmayBhosale** [TanmayBhosale/open-nova#2]
Define all the rules that the contributor must follow. Details steps to make contribution.

**Comment by SubhamChoudhury** [comment]
Hey @TanmayBhosale, can I take this up?

**Comment by TanmayBhosale** [comment]
Yup sure

**Comment by TanmayBhosale** [comment]
Hey, any updates?

**Comment by CodingWarrior33** [comment]
Hey I want to contribute to this...

**Comment by SubhamChoudhury** [comment]
Hey @TanmayBhosale, extremely sorry for the delay. Raising the PR soon, almost done!

**Comment by TanmayBhosale** [comment]
Yup sue np

**Comment by TanmayBhosale** [comment]
solved in PR #9
