### ISSUE TITLE
Fix tweet component bugs

### ISSUE THREAD

**Issue by rohitdalvi18** [TanmayBhosale/open-nova#21]
Bugs:

1. Circumference of circular progress of character count is not accurate which affects the the progress bar
2. Text Area of tweet is not auto resizing dynamically and border is visible on focus
3. Length of tweet thread connector is static at the moment, it should increase dynamically 
4. User should be notified while drafting a tweet if tweet character limit is reached
5. Circular progress of character count is static at the moment

**Comment by rohitdalvi18** [comment]
I can help resolve these bugs :)

**Comment by TanmayBhosale** [comment]
Go ahead!
