### ISSUE TITLE
💡 [ENHANCEMENT] - Create a palette

### ISSUE THREAD

**Issue by TanmayBhosale** [TanmayBhosale/open-nova#25]
### Is your enhancement proposal related to a problem?

Currently, the website supports only dark mode. As most of the modern websites support both dark and light modes, it would be good to have enhancement.

### Describe the desired solution you'd like

To implement light and dark mode, we need to update the color palette in the tailwind config file. You can get the colors from the figma file.

**Comment by rutujaranade24** [comment]
I can work on this!

**Comment by TanmayBhosale** [comment]
Sure go ahead!
