### ISSUE TITLE
Create Dashboard Page

### ISSUE THREAD

**Issue by TanmayBhosale** [TanmayBhosale/open-nova#5]
Design a Dashboard Page as in the designs

**Comment by gunjansaha55** [comment]
Please assigned me into this issue I will fix this.

**Comment by TanmayBhosale** [comment]
Sure go ahead. Just make sure you use colors from the global stylesheet and not directly define it in the components page

**Comment by TanmayBhosale** [comment]
Hey, @gunjansaha55 any updates?

**Comment by gunjansaha55** [comment]
@TanmayBhosale I face some issues but I can't fix them so please unassigned me sorry for time wasting.

**Comment by TanmayBhosale** [comment]
Fix: #28
