### ISSUE TITLE
Create new tweet screen

### ISSUE THREAD

**Issue by TanmayBhosale** [TanmayBhosale/open-nova#7]
Create the new tweet screen as per the designs

**Comment by burhanharoon** [comment]
Hy, I want to work on it but the figma design is not visible!

**Comment by TanmayBhosale** [comment]
Thank you for mentioning the issue! I have fixed it. Currently, someone is working on this issue. Would you like to work on some other page? Maybe the dashboard page

**Comment by rohitdalvi18** [comment]
@TanmayBhosale can you please assign it to me, to avoid any confusion?

**Comment by TanmayBhosale** [comment]
Yup

**Comment by TanmayBhosale** [comment]
fix: #11
